import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import api from '../../services/api';
import RouteMap from '../../components/routes/RouteMap';
import PlaceSearch from '../../components/routes/PlaceSearch';
import './RoutesStops.css';
const classifications = { waiting_for_parent_location: 'Waiting for parent location', not_riding: 'Not currently riding', temporary_arrangement: 'Temporary arrangement', parent_transport: 'Parent transport', starts_later: 'Transport starts later' };
const blankStop = { name: '', location: null, formattedAddress: '', placeId: '', studentIds: [], geofenceRadiusMeters: 65, expiresAt: '', reviewNote: '', confirmedWithParent: false };
export default function RoutesStops() {
  const [buses, setBuses] = useState([]), [busId, setBusId] = useState(''), [data, setData] = useState(null);
  const [direction, setDirection] = useState('TO_SCHOOL'), [morning, setMorning] = useState([]), [returning, setReturning] = useState([]), [classified, setClassified] = useState({});
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [preview, setPreview] = useState(null), [editor, setEditor] = useState(null), [request, setRequest] = useState(null), [mergeId, setMergeId] = useState('');
  const [schoolEditor, setSchoolEditor] = useState(null), [effective, setEffective] = useState(''), [confirmUnresolved, setConfirmUnresolved] = useState(false), [versions, setVersions] = useState([]), [dirty, setDirty] = useState(false);
  const drag = useRef(null), generation = useRef(0);
  const load = useCallback(async () => {
    if (!busId) return;
    const ticket = ++generation.current; setLoading(true);
    try {
      const { data: result } = await api.get(`/school/buses/${busId}/route-summary`);
      if (ticket !== generation.current) return;
      setData(result); setMorning(result.draft?.morningStopIds || []); setReturning(result.draft?.returnStopIds || []);
      setClassified(Object.fromEntries((result.draft?.unresolvedStudents || []).map(s => [s.studentId, s.classification])));
      setDirty(false); setPreview(null);
    } catch (e) { setError(e.response?.data?.message || 'Could not load this bus route.'); }
    finally { if (ticket === generation.current) setLoading(false); }
  }, [busId]);
  useEffect(() => { let cancelled = false; api.get('/buses').then(({ data: result }) => { if (cancelled) return; setBuses(result.buses || []); setBusId(result.buses?.[0]?._id || ''); }).catch(() => setError('Could not load buses.')).finally(() => setLoading(false)); return () => { cancelled = true; }; }, []);
  useEffect(() => { setData(null); setEditor(null); setRequest(null); load(); }, [load]);
  useEffect(() => { if (!dirty) return; const warn = e => { e.preventDefault(); e.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  async function perform(fn, message, refresh = true) {
    setBusy(true); setError(''); setNotice('');
    try { await fn(); if (refresh) await load(); if (message) setNotice(message); return true; }
    catch (e) { setError(e.response?.data?.message || 'Could not save. Please try again.'); return false; }
    finally { setBusy(false); }
  }
  const order = direction === 'TO_SCHOOL' ? morning : returning;
  const setOrder = next => { direction === 'TO_SCHOOL' ? setMorning(next) : setReturning(next); setDirty(true); setPreview(null); };
  const stops = useMemo(() => order.map(sid => data?.stops.find(s => s._id === sid)).filter(Boolean), [order, data]);
  const unresolved = useMemo(() => (data?.students || []).filter(student => !morning.some(sid => data.stops.find(s => s._id === sid && s.active)?.studentIds.includes(student._id)) || !returning.some(sid => data.stops.find(s => s._id === sid && s.active)?.studentIds.includes(student._id)) || ['not_riding', 'parent_transport', 'starts_later'].includes(student.transportStatus)), [data, morning, returning]);
  function move(from, to) { if (to < 0 || to >= order.length || from === to) return; const next = [...order], [item] = next.splice(from, 1); next.splice(to, 0, item); setOrder(next); }
  const draftBody = () => ({ morningStopIds: morning, returnStopIds: returning, expectedRevision: data.bus.routeRevision, unresolvedStudents: Object.entries(classified).filter(([, value]) => value).map(([studentId, classification]) => ({ studentId, classification })) });
  async function save() { return perform(() => api.put(`/school/buses/${busId}/route-plan`, draftBody()), 'Draft saved. Published trips are unchanged.'); }
  async function previewRoute() {
    if (dirty) { setError('Save your draft before previewing.'); return; }
    await perform(async () => { const { data: result } = await api.post(`/school/buses/${busId}/route-preview`, { direction, ...(effective ? { effectiveFrom: new Date(effective).toISOString() } : {}) }); setPreview(result); }, '', false);
  }
  async function publishRoute() {
    if (dirty) { setError('Save your draft before publishing.'); return; }
    if (!window.confirm('Publish a new route version for future trips? Active trips will keep their existing stops.')) return;
    await perform(() => api.post(`/school/buses/${busId}/route-publish`, { ...(effective ? { effectiveFrom: new Date(effective).toISOString() } : {}), confirmUnresolved }), 'New route version published.');
  }
  async function review(status) {
    if (!editor) return;
    const ok = await perform(() => api.patch(`/school/pickup-requests/${request._id}/review`, { ...editor, status, routeStopId: mergeId || undefined, expiresAt: editor.expiresAt ? new Date(editor.expiresAt).toISOString() : null, expectedRevision: data.bus.routeRevision }), 'Pickup request reviewed.');
    if (ok) { setEditor(null); setRequest(null); setMergeId(''); }
  }
  async function saveStop() {
    const payload = { ...editor, expiresAt: editor.expiresAt ? new Date(editor.expiresAt).toISOString() : null, expectedRevision: data.bus.routeRevision };
    const ok = await perform(() => editor._id ? api.patch(`/school/buses/${busId}/stops/${editor._id}`, payload) : api.post(`/school/buses/${busId}/stops`, payload), 'Stop saved to the draft.');
    if (ok) setEditor(null);
  }
  function openEditor(value, pickup = null) { if (dirty && !window.confirm('Discard unsaved stop ordering before editing a stop?')) return; setEditor(value); setRequest(pickup); setMergeId(''); }
  return <main className="routes-workspace">
    <header className="route-header"><div><h1>Routes &amp; Stops</h1><p>Review pickup points, arrange both journeys, and publish with confidence.</p></div><button onClick={() => setSchoolEditor({ ...(data?.schoolLocation || { lat: 26.1445, lng: 91.7362 }), confirmed: false })}>Set school location</button></header>
    {error && <div className="route-error" role="alert">{error}</div>}{notice && <div className="route-notice" role="status">{notice}</div>}
    <div className="route-grid">{buses.map(bus => <button key={bus._id} aria-pressed={busId === bus._id} onClick={() => { if (dirty && !window.confirm('Discard unsaved changes?')) return; setBusId(bus._id); }}><strong>{bus.busNumber}</strong><small>{bus.driverId?.fullName || 'Driver not assigned'} · {bus.studentCount || 0} students</small></button>)}</div>
    {loading && <div className="route-card" role="status">Loading route…</div>}
    {!loading && !buses.length && <div className="route-card">Add a bus in Buses to begin planning a route.</div>}
    {data && !loading && <>
      <div className="route-card route-row"><div><strong>{data.bus.busNumber}</strong><div>{data.counts.students} students · {data.counts.approvedStops} stops · {data.counts.sharedStops} shared stops</div><span className="route-badge warn">{data.counts.pending} pending · {data.counts.missingLocations} without locations</span><span className="route-badge">{data.published ? `Published v${data.published.version}` : 'No published route'}</span><span className={`route-badge ${data.ready ? '' : 'warn'}`}>{data.ready ? 'Ready for final review' : 'Review required'}</span>{data.published && <small className="route-muted">Effective {new Date(data.published.effectiveFrom).toLocaleString()}</small>}</div><button disabled={busy} onClick={() => perform(async () => { const { data: result } = await api.get(`/school/buses/${busId}/route-versions`); setVersions(result.versions); }, '', false)}>Version history</button></div>
      {versions.length > 0 && <div className="route-card">{versions.map(v => <p key={v._id}>Version {v.version} · Effective {new Date(v.effectiveFrom).toLocaleString()}</p>)}<button onClick={() => setVersions([])}>Close history</button></div>}
      <div className="route-tabs" role="tablist" aria-label="Journey direction"><button role="tab" aria-selected={direction === 'TO_SCHOOL'} onClick={() => { setDirection('TO_SCHOOL'); setPreview(null); }}>Morning Pickup</button><button role="tab" aria-selected={direction === 'FROM_SCHOOL'} onClick={() => { setDirection('FROM_SCHOOL'); setPreview(null); }}>Return Drop-off</button></div>
      <div className="route-split"><section>
        <div className="route-card"><RouteMap stops={stops} school={data.schoolLocation} selected={editor?.location} onSelect={editor ? location => setEditor({ ...editor, location, formattedAddress: '', placeId: '' }) : undefined} remainingPolyline={preview?.routePolyline} />{editor && <p className="route-muted">Tap the map or drag the selected marker to adjust this stop.</p>}{preview && <p><strong>{(preview.routeDistanceMeters / 1000).toFixed(1)} km · {Math.ceil(preview.routeDurationSeconds / 60)} min</strong><small className="route-muted"> · Preview starts at school; morning trips use the driver’s actual starting point.</small></p>}</div>
        <div className="route-card"><div className="route-row"><h2>Pending pickup requests</h2><span className="route-badge">{data.requests.length}</span></div>{!data.requests.length && <p className="route-muted">All pickup requests have been reviewed.</p>}<div className="route-queue">{data.requests.map(r => <article key={r._id}><strong>{data.students.find(s => s._id === r.studentId)?.name || 'Student'}</strong><small>{r.formattedAddress || 'Point selected on map'}</small><p className="route-muted">{r.status.replaceAll('_', ' ')}</p>{data.suggestions.find(s => s.requestId === r._id)?.stops.map(s => <span className="route-badge" key={s.id}>Nearby: {s.name} · {s.distanceMeters} m</span>)}<div><button disabled={busy} onClick={() => openEditor({ ...blankStop, name: 'Pickup stop', location: r.requestedLocation, formattedAddress: r.formattedAddress, placeId: r.placeId, studentIds: [r.studentId] }, r)}>Review on map</button></div></article>)}</div></div>
      </section><section>
        <div className="route-card"><div className="route-row"><h2>Stop order</h2><span className="route-badge">{order.length} stops{dirty ? ' · Unsaved' : ''}</span></div><p className="route-muted">Drag stops or use the arrow buttons. Each direction has its own order.</p><ol className="route-list route-list-scroll">{stops.map((stop, index) => <li key={stop._id} draggable onDragStart={() => { drag.current = index; }} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (drag.current !== null) move(drag.current, index); drag.current = null; }}><span className="stop-number">{index + 1}</span><div className="stop-text"><strong>{stop.name}</strong><small>{stop.studentIds.length} students · {stop.active ? 'Active' : 'Inactive'}{stop.expiresAt ? ` · Until ${new Date(stop.expiresAt).toLocaleDateString()}` : ''}</small></div><button aria-label={`Move ${stop.name} up`} disabled={index === 0} onClick={() => move(index, index - 1)}>↑</button><button aria-label={`Move ${stop.name} down`} disabled={index === stops.length - 1} onClick={() => move(index, index + 1)}>↓</button><button onClick={() => openEditor({ ...blankStop, ...stop, expiresAt: stop.expiresAt?.slice(0, 10) || '', confirmedWithParent: false })}>Edit</button><button aria-label={`Remove ${stop.name} from this direction`} onClick={() => { if (window.confirm('Remove this stop from this direction in the draft?')) setOrder(order.filter(sid => sid !== stop._id)); }}>×</button></li>)}</ol>{!stops.length && <p className="route-muted">Approve a pickup request or create a stop to start this route.</p>}
          <label>Add an existing stop<select value="" onChange={e => e.target.value && setOrder([...order, e.target.value])}><option value="">Choose a stop</option>{data.stops.filter(s => s.active && !order.includes(s._id)).map(s => <option key={s._id} value={s._id}>{s.name}</option>)}</select></label>
          <div className="route-actions"><button disabled={busy} onClick={() => openEditor({ ...blankStop })}>Create stop</button>{direction === 'FROM_SCHOOL' && <button onClick={() => { if (window.confirm('Replace the return order with the reverse of the morning order?')) setOrder([...morning].reverse()); }}>Reverse morning order</button>}<button disabled={busy} className="route-primary" onClick={save}>Save draft</button><button disabled={busy || dirty || !order.length} onClick={previewRoute}>Preview route</button></div>
        </div>
        {editor && <div className="route-card route-editor"><h2>{request ? 'Review pickup location' : editor._id ? 'Edit stop' : 'Create stop'}</h2><PlaceSearch bias={data.schoolLocation} onSelect={place => setEditor({ ...editor, ...place })} /><label>Stop name<input value={editor.name} onChange={e => setEditor({ ...editor, name: e.target.value })} /></label><p className="route-muted">{editor.formattedAddress || (editor.location ? 'Map point selected' : 'Choose a location on the map')}</p>
          {request ? <label>Merge into an approved stop<select value={mergeId} onChange={e => setMergeId(e.target.value)}><option value="">Create a separate stop</option>{data.stops.filter(s => s.active).map(s => <option key={s._id} value={s._id}>{s.name} · {s.studentIds.length} students</option>)}</select></label> : <><label>Students at this stop</label><div className="route-students">{data.students.map(s => <label key={s._id}><input type="checkbox" checked={editor.studentIds.includes(s._id)} onChange={e => setEditor({ ...editor, studentIds: e.target.checked ? [...editor.studentIds, s._id] : editor.studentIds.filter(v => v !== s._id) })} />{s.name} · {s.class}</label>)}</div></>}
          <label>School note<textarea value={editor.reviewNote} onChange={e => setEditor({ ...editor, reviewNote: e.target.value })} placeholder="Explain an adjustment or ask for clarification" /></label><label>Temporary stop expiry (optional)<input type="date" value={editor.expiresAt} onChange={e => setEditor({ ...editor, expiresAt: e.target.value })} /></label><label>Arrival radius (metres)<input type="number" min="30" max="150" value={editor.geofenceRadiusMeters} onChange={e => setEditor({ ...editor, geofenceRadiusMeters: Number(e.target.value) })} /></label>
          {!request && <label><input type="checkbox" checked={editor.confirmedWithParent} onChange={e => setEditor({ ...editor, confirmedWithParent: e.target.checked })} />I have confirmed the location and student assignment with the parent.</label>}
          <div className="route-actions">{request ? <><button disabled={busy || (!editor.location && !mergeId)} className="route-primary" onClick={() => review('approved')}>Approve / merge</button><button disabled={busy || !editor.reviewNote.trim()} onClick={() => review('adjusted')}>Approve adjusted point</button><button disabled={busy || !editor.reviewNote.trim()} onClick={() => review('clarification_required')}>Ask for clarification</button><button disabled={busy || !editor.reviewNote.trim()} className="route-danger" onClick={() => review('rejected')}>Reject</button></> : <><button disabled={busy || !editor.location || !editor.name} className="route-primary" onClick={saveStop}>Save stop</button>{editor._id && <button disabled={busy} onClick={() => { if (window.confirm(`${editor.active ? 'Deactivate' : 'Activate'} this stop for future route planning?`)) perform(() => api.patch(`/school/buses/${busId}/stops/${editor._id}`, { active: !editor.active, expectedRevision: data.bus.routeRevision }), 'Stop status updated.').then(ok => { if (ok) setEditor(null); }); }}>{editor.active ? 'Deactivate' : 'Activate'}</button>}</>}<button onClick={() => { setEditor(null); setRequest(null); }}>Cancel</button></div>
        </div>}
        <div className="route-card"><h2>Students needing route review</h2><p className="route-muted">Student addresses remain informational. An approved map stop is required for a personal ETA.</p><div className="route-queue">{data.students.filter(s => !s.routeStopId || unresolved.some(u => u._id === s._id)).map(s => <article key={s._id}><strong>{s.name}</strong><span className="route-badge warn">{s.stage}</span><small className="route-muted">Address: {s.address}</small><label>Arrangement<select value={classified[s._id] || ''} onChange={e => { setClassified({ ...classified, [s._id]: e.target.value }); setDirty(true); }}><option value="">Choose a classification</option>{Object.entries(classifications).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button disabled={busy} onClick={() => openEditor({ ...blankStop, studentIds: [s._id], name: `${s.name}'s stop` })}>Assign a stop</button></article>)}</div><details><summary>Manage transport participation</summary>{data.students.map(s => <div key={s._id}><label>{s.name}<select value={s.transportStatus || 'active'} disabled={busy} onChange={e => { const status = e.target.value; if (status === 'starts_later') { setNotice('Choose a start date below, then save it.'); return; } perform(() => api.patch(`/school/students/${s._id}/transport`, { transportStatus: status }), 'Transport status updated.'); }}><option value="active">Using transport</option><option value="not_riding">Not currently riding</option><option value="parent_transport">Parent transport</option><option value="temporary_arrangement">Temporary arrangement</option><option value="starts_later">Starts later</option></select></label><label>Start transport on<input type="date" onChange={e => { if (e.target.value && window.confirm('Set this future transport start date?')) perform(() => api.patch(`/school/students/${s._id}/transport`, { transportStatus: 'starts_later', transportStartsAt: new Date(e.target.value).toISOString() }), 'Future transport date saved.'); }} /></label></div>)}</details></div>
        <div className="route-card"><h2>Publish a route version</h2><label>Effective from (leave blank for now)<input type="datetime-local" value={effective} onChange={e => setEffective(e.target.value)} /></label><p className="route-muted">Active trips retain their current route. Publishing creates a new version.</p><label><input type="checkbox" checked={confirmUnresolved} onChange={e => setConfirmUnresolved(e.target.checked)} />I reviewed every unresolved student’s arrangement and confirm publication with those students excluded where applicable.</label><button className="route-primary" disabled={busy || dirty || !morning.length || !returning.length} onClick={publishRoute}>{busy ? 'Please wait…' : 'Publish new version'}</button></div>
      </section></div>
    </>}
    {schoolEditor && <div className="route-modal" role="dialog" aria-modal="true" aria-label="School location"><div className="route-card"><h2>School location</h2><PlaceSearch onSelect={place => setSchoolEditor({ ...schoolEditor, ...place.location, formattedAddress: place.formattedAddress, placeId: place.placeId })} /><RouteMap stops={[]} selected={{ lat: schoolEditor.lat, lng: schoolEditor.lng }} onSelect={point => setSchoolEditor({ ...schoolEditor, ...point, formattedAddress: '', placeId: '' })} height={330} /><p className="route-muted">{schoolEditor.formattedAddress || 'Select the school entrance on the map.'}</p><label><input type="checkbox" checked={schoolEditor.confirmed} onChange={e => setSchoolEditor({ ...schoolEditor, confirmed: e.target.checked })} />This is the correct school entrance for the bus.</label><div className="route-actions"><button className="route-primary" disabled={busy || !schoolEditor.confirmed} onClick={() => perform(() => api.put('/school/location', schoolEditor), 'School location saved.').then(ok => { if (ok) setSchoolEditor(null); })}>Save school location</button><button onClick={() => setSchoolEditor(null)}>Cancel</button></div></div></div>}
  </main>;
}
